replicaCount: 1

name: "app-integrity-and-misconfiguration-validation-webhhook"

image:
  name: kensenh/simple-kubernetes-webhook
  pullPolicy: Always
  tag: "latest"

service:
  type: ClusterIP
  port: 80

resources: {}