backendStorage:
  artifacts-bucket-name: "gather-n-upload-artifacts"
  public-keys-bucket-name: "gather-n-upload-public-keys"
  log-bucket-name: "event-log"
rules:
  owasp-dependency-check:
    max-critical-severity: 5
    max-high-severity: 5
    max-medium-serverity: 10
    max-low-severity: 0
    acceptable-base-score:
      attack-vector: "NETWORK" #(NETWORK, ADJACENT, LOCAL, PHYSICAL)
      attack-complexity: "LOW" #(LOW, HIGH)
      privileges-required: "NONE" #(NONE, LOW, HIGH)
      user-interaction: "NONE" #(NONE, REQUIRED)
      scope: "CHANGED" #(UNCHANGED, CHANGED)s
      confidentiality-impact: "HIGH" #(NONE, LOW, HIGH)
      integrity-impact: "HIGH" #(NONE, LOW, HIGH)
      availability-impact: "HIGH" #(NONE, LOW, HIGH)
  kubesec:
    min-score: 0
namespaceRestricted:
  - default
