apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}
          imagePullPolicy: Always
          env:
            - name: TLS
              value: "true"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/admission-webhook/credential/credential.json"
          volumeMounts:
            - name: tls
              mountPath: "/etc/admission-webhook/tls"
            - name: credential
              mountPath: "/etc/admission-webhook/credential"
      volumes:
        - name: tls
          secret:
            secretName: webhook-tls
        - name: credential
          secret:
            secretName: gcp